// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhzdiujstclkpcnoriwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpoemRpdWpzdGNsa3Bjbm9yaXdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzMTQ1MTUsImV4cCI6MjA1NDg5MDUxNX0.OdNxH5NueByZH_Pmgg3NrxvXIy6dKWHHDUgX-0if0ws";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);