// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rkgjjsacflxamaqxoljg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJrZ2pqc2FjZmx4YW1hcXhvbGpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MTI5NjIsImV4cCI6MjA2MDk4ODk2Mn0.jxzxE6ZAApyr32NIg7rCtadbqdfQBQVkbdjQe5H5SNU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);